/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shape3d2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Shape3d2(props) {
  const { nodes, materials } = useGLTF('/shape3d2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-1.439, 1.26, 0]} />
    </group>
  )
}

useGLTF.preload('/shape3d2.gltf')
